# Generated by Django 4.1.1 on 2022-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_musicstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField()),
            ],
        ),
    ]
