# Generated by Django 4.1.2 on 2022-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_searchtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='rank',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
