# Generated by Django 4.1.2 on 2022-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_date_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='musicstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='musicstatus',
            name='duration_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicstatus',
            name='instrumentalness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicstatus',
            name='speechiness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicstatus',
            name='tempo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='mode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='track_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
