# Generated by Django 4.1.2 on 2022-11-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_musicstatus_img300_musicstatus_img64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicstatus',
            name='img300',
        ),
        migrations.RemoveField(
            model_name='musicstatus',
            name='img64',
        ),
        migrations.RemoveField(
            model_name='musicstatus',
            name='img640',
        ),
        migrations.AddField(
            model_name='musicstatus',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
