# Generated by Django 4.1.2 on 2022-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_remove_musicstatus_img300_remove_musicstatus_img64_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top100ByDate',
            fields=[
                ('date', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rank', models.TextField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('valence', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
