# Generated by Django 4.1.2 on 2022-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_top100bydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('track_id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('img640', models.TextField()),
                ('img300', models.TextField()),
                ('img64', models.TextField()),
            ],
        ),
    ]
