# Generated by Django 4.1.2 on 2022-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='artist',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
