# Generated by Django 4.1.1 on 2022-11-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_albumimage_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicstatus',
            name='acousticness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='danceability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='instrumentalness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='loudness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='speechiness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='musicstatus',
            name='valence',
            field=models.FloatField(null=True),
        ),
    ]
