# Generated by Django 4.1.1 on 2022-11-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_alter_musicstatus_acousticness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicstatus',
            name='popularity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
