# Generated by Django 4.1.2 on 2022-11-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0017_remove_date_date_date_end_date_date_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='date',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='date',
            name='start_date',
        ),
    ]
