# Generated by Django 4.1.2 on 2022-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0018_period_rename_end_date_date_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
        ),
    ]
