# Generated by Django 4.1.2 on 2022-11-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0020_musicstatus_artist_id_musicstatus_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicstatus',
            name='genre',
        ),
    ]
