# Generated by Django 4.1.2 on 2022-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0021_remove_musicstatus_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.TextField()),
                ('artist_id', models.TextField()),
            ],
        ),
    ]
