# Generated by Django 4.1.2 on 2022-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0024_artistinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='artistinfo',
            name='artist_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
