# Generated by Django 4.1.2 on 2022-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0026_rename_realted_artists_artistinfo_related_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTopTracks',
            fields=[
                ('artist_id', models.TextField(primary_key=True, serialize=False)),
                ('top_tracks', models.TextField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('valence', models.FloatField()),
                ('mode', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='top_tracks',
        ),
    ]
