# Generated by Django 4.1.2 on 2022-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0028_statusinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinput',
            name='input',
            field=models.FloatField(),
        ),
    ]
