# Generated by Django 4.1.2 on 2022-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0029_alter_statusinput_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top100bydate',
            name='acousticness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='danceability',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='duration_ms',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='energy',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='instrumentalness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='liveness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='loudness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='mode',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='speechiness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='tempo',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='top100bydate',
            name='valence',
            field=models.FloatField(default=None, null=True),
        ),
    ]
